### ISSUE TITLE
attempt to index global 'thermalvision'

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-wep_doorlocker#1]
[ERROR] addons/ttt2-wep_doorlocker-master/gamemodes/terrortown/entities/weapons/weapon_ttt_doorlocker.lua:101: attempt to index global 'thermalvision' (a nil value)
  1. fn - addons/ttt2-wep_doorlocker-master/gamemodes/terrortown/entities/weapons/weapon_ttt_doorlocker.lua:101
   2. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

Tested and all works fine but when take on my hand the doorlocker, this error appear in console

**Comment by TimGoll** [comment]
It does not work on the master branch. You have to manually merge the thermanvision branch into the master branch to use it

**Comment by ThePlatinumGhost** [comment]
ah okey thanks
